FROM antonapetrov/uvicorn-gunicorn-fastapi:python3.10-slim

ENV APP_MODULE=bot:app
ENV MAX_WORKERS=1

ENV TZ=Asia/Shanghai

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime

COPY ./ /app/

WORKDIR /app

RUN python3 -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && python3 -m pip install poetry && poetry source add --default aliyun https://mirrors.aliyun.com/pypi/simple/ && poetry add dist/*.whl && poetry install
