FROM pypy:3.9

ENV TZ=Asia/Shanghai

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime

COPY ./ /app/

WORKDIR /app

# 需要使用清华源的话替换为下面这条语句
RUN python3 -m pip install poetry && poetry install
# RUN python3 -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && python3 -m pip install poetry && poetry source add --default aliyun https://mirrors.aliyun.com/pypi/simple/ && poetry install

CMD ["poetry", "run", "nb", "run"]
